config/routes.rb
# This file is a part of Redmine Tags (redmine_tags) plugin,
# customer relationship management plugin for Redmine
#
# Copyright (C) 2011-2019 RedmineUP
# http://www.redmineup.com/
#
# redmine_tags is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_tags is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_tags.  If not, see <http://www.gnu.org/licenses/>.

RedmineApp::Application.routes.draw do
  match '/issue_tags/auto_complete/:project_id', to: 'auto_completes#issue_tags', via: :get, as: 'auto_complete_issue_tags'
  match '/wiki_tags/auto_complete/:project_id', to: 'auto_completes#wiki_tags', via: :get, as: 'auto_complete_wiki_tags'
  match 'auto_completes/redmine_tags' => 'auto_completes#redmine_tags', via: :get, as: 'auto_complete_redmine_tags'
  match '/tags/context_menu', to: 'tags#context_menu', as: 'tags_context_menu', via: [:get, :post]
  match '/tags', controller: 'tags', action: 'destroy', via: :delete
end

resources :tags, only: [:edit, :update] do
  collection do
    post :merge
    get :context_menu, :merge
  end
end

get :edit_issue_tags, to: 'issue_tags#edit'
post :update_issue_tags, to: 'issue_tags#update'

app/controllers/issue_tags_controller.rb
# This file is a part of Redmine Tags (redmine_tags) plugin,
# customer relationship management plugin for Redmine
#
# Copyright (C) 2011-2019 RedmineUP
# http://www.redmineup.com/
#
# redmine_tags is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_tags is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_tags.  If not, see <http://www.gnu.org/licenses/>.

class IssueTagsController < ApplicationController
  unloadable

  before_action :find_issues, only: [:edit, :update]

  def edit
    return unless User.current.allowed_to?(:edit_tags, @projects.first)
    @issue_ids = params[:ids]
    @is_bulk_editing = @issue_ids.size > 1
    @issue_tags = @is_bulk_editing ? @issues.map(&:tag_list).flatten.uniq : @issues.first.tag_list
    @most_used_tags = Issue.all_tags(sort_by: 'count', order: 'DESC').limit(10)
  end

  def update
    if User.current.allowed_to?(:edit_tags, @projects.first)
      tags = params[:issue] && params[:issue][:tag_list] ? params[:issue][:tag_list].reject(&:empty?) : []

      unless User.current.allowed_to?(:create_tags, @projects.first) || Issue.allowed_tags?(tags)
        flash[:error] = t(:notice_failed_to_add_tags)
        return
      end

      Issue.transaction do
        @issues.each do |issue|
          issue.tag_list = tags
          issue.save!
        end
      end
      flash[:notice] = t(:notice_tags_added)
    else
      flash[:error] = t(:notice_failed_to_add_tags)
    end
  rescue Exception => e
    puts e
    flash[:error] = t(:notice_failed_to_add_tags)
  ensure
    redirect_to_referer_or { render text: 'Tags updated.', layout: true }
  end
end

app/views/issue_tags/_edit_modal.html.erb
<h3 class="title"><%= l(:label_add_tags) %></h3>

<% if @is_bulk_editing %>
  <h3><%= l(:label_bulk_edit_selected_issues) %></h3>
  <ul>
    <% @issues.each do |issue| %>
        <%= content_tag 'li', link_to_issue(issue) %>
    <% end %>
  </ul>
<% else %>
    <h3><%= content_tag 'span', link_to_issue(@issues.first) %></h3>
<% end %>


<%= form_tag(update_issue_tags_path(:ids => @issue_ids),
             :method => :post,
             :id => 'edit-issue-tags-form') do %>

    <fieldset class="box">
      <legend><%= l(:tags) %></legend>
      <div id="issue_tags">
        <%= select2_tag 'issue[tag_list]',
                        options_for_select(@issue_tags.map{ |tag| [tag, tag] }, @issue_tags),
                        :multiple => true,
                        :style => 'width: 100%;',
                        :url => auto_complete_redmine_tags_path,
                        :placeholder => @is_bulk_editing ? t(:label_no_change_option) : '+ add tag',
                        :tags => User.current.allowed_to?(:create_tags, @project) %>
      </div>

      <p class="most_used_tags">
        <%= safe_join(@most_used_tags.collect { |t| content_tag('span', t.name, :class => 'most_used_tag') }, ', ') %>
      </p>
      <%= javascript_tag "var mostUsedTags = #{@most_used_tags.map(&:name)}" %>
    </fieldset>

    <div class="buttons">
      <%= submit_tag l(:button_add), :name => nil %>
      <%= submit_tag l(:button_cancel), :name => nil, :onclick => "hideModal(this);", :type => 'button' %>
    </div>
<% end %>

app/views/issue_tags/edit.js.erb
$('#ajax-modal').html('<%= escape_javascript(render :partial => 'issue_tags/edit_modal') %>');
showModal('ajax-modal', '600px');